set MBPT_API_CLIENT_ID=mbpt-ng5
set MBPT_API_CLIENT_SECRET=kkNo4Vp9kIt3Nngs0E8mjo0SI8niF43ylXLEhiKZVhAhmNiLTSWWh9CtiJMKA30YgFLXYDN2o8wpIEuhARHybbnnPXK3AhUPDudL7efc7P7VYHO7b3OB3GMyh8vhBZrG
set MBPT_AUTH_URI=https://mbpt-api.herokuapp.com/auth/token
set MBPT_SOCIAL_AUTH_URI=https://mbpt-api.herokuapp.com/auth/convert-token
